# Generated by Django 4.0.6 on 2022-08-04 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_post', '0003_videopost_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videopost',
            name='followers',
        ),
    ]
